const SOMETHING_WENT_WRONG = "Something went wrong.";
const NOT_FOUND = "NOT FOUND";
const ACCESS_TOKEN_EXPIRY = "1d";
const REFRESH_TOKEN_EXPIRY = "7d";

module.exports = {
  SOMETHING_WENT_WRONG,
  NOT_FOUND,
  REFRESH_TOKEN_EXPIRY,
  ACCESS_TOKEN_EXPIRY,
};
